// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../nclosure-docs/tutorial/4/deps.js', [], []);
goog.addDependency('../../../../../nclosure-docs/tutorial/4/fileinfo.js', ['demo.fileinfo'], ['goog.debug']);
goog.addDependency('../../../../../nclosure-docs/tutorial/4/listfiles.js', ['demo.listfiles'], ['demo.fileinfo', 'goog.array']);
