// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../nclosure-docs/tutorial/2/deps.js', [], []);
goog.addDependency('../../../../../nclosure-docs/tutorial/2/fileinfo.js', ['demo.fileinfo'], ['goog.debug']);
goog.addDependency('../../../../../nclosure-docs/tutorial/2/listfiles.js', ['demo.listfiles'], ['demo.fileinfo', 'goog.array']);
goog.addDependency('../../../../../nclosure-docs/tutorial/2/tests/allTests.js', [], ['demo.fileinfo', 'goog.testing.jsunit']);
goog.addDependency('../../../../../nclosure-docs/tutorial/2/tests/testingSuite.js', [], []);
