// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../nclosure-docs/tutorial/3/docs/javascript/all.js', [], []);
goog.addDependency('../../../../../nclosure-docs/tutorial/3/docs/javascript/html5.js', [], []);
goog.addDependency('../../../../../nclosure-docs/tutorial/3/docs/javascript/prettify.js', [], []);
goog.addDependency('../../../../../nclosure-docs/tutorial/3/fileinfo.js', ['demo.fileinfo'], ['goog.debug']);
goog.addDependency('../../../../../nclosure-docs/tutorial/3/listfiles.js', ['demo.listfiles'], ['demo.fileinfo', 'goog.array']);
